config/routes.rb
Reddit::Application.routes.draw do
  resources :users
  resources :links, :except => :index do
    get '/comments/:id' => 'comments#show', :as => 'comment'
    post '/comments' => 'comments#create'

  end

  resources :subs do
    resources :links, :only => [:index]
  end




  get '/login' => 'session#new'
  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :link_id, :author_id, :parent_comment

  belongs_to :author, class_name: 'User'
  belongs_to :link

  has_many :sub_replies, class_name: 'Reply', foreign_key: :parent_comment_id
  has_many :sub_comments, through: :sub_replies, source: :sub_comment

  has_one :parent_reply, class_name: 'Reply', foreign_key: :sub_comment_id

  has_one :parent_comment, through: :parent_reply, source: :parent_comment

  def self.build_comment_tree(comments)
    built_tree = []
    comment_tree = comments.reverse
    while child = comment_tree.pop
      built_tree << child
      sub_comments = child.sub_comments
      next if sub_comments.empty?
      comment_tree += sub_comments
    end
    built_tree
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :title, :url,
                  :submitter_id

  belongs_to :submitter, class_name: 'User'

  has_many :link_subs
  has_many :subs, through: :link_subs

  has_many :comments
  has_many :sub_comments, through: :comments
end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  attr_accessible :link_id, :sub_id

  belongs_to :link
  belongs_to :sub
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :parent_comment_id, :sub_comment_id
  belongs_to :parent_comment, class_name: 'Comment',
    foreign_key: :parent_comment_id,
    primary_key: :id
  belongs_to :sub_comment, class_name: 'Comment',
    foreign_key: :sub_comment_id,
    primary_key: :id
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :moderator_id, :name, :links_attributes
  has_many :link_subs
  has_many :links, through: :link_subs
  belongs_to :moderator, class_name: 'User'
  accepts_nested_attributes_for :links, :reject_if => :all_blank
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password
  has_many :submitted_links,
    class_name: 'Link',
    foreign_key: :submitter_id

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def authenticate_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token
    self.session_token = SecureRandom.base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include ApplicationHelper
  def authenticate_user
    redirect_to login_url unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user

  def show
    @link = Link.find(params[:link_id])
    @comment = Comment.find(params[:id])
    @replies = @comment.sub_comments.select { |comment| comment.parent_comment == @comment }
  end

  def new
  end

  def create
    @parent = Comment.find(params[:parent_comment]) if params[:parent_comment]
    if @parent
      @comment = @parent.sub_comments.build(params[:comment])
      @parent.save
      redirect_to link_url(@comment.link_id)
    else
      @comment = Comment.new(params[:comment])
      @comment.save
      redirect_to link_url(@comment.link_id)
    end
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authenticate_user

  def index
    @links = Sub.find(params[:sub_id]).links
  end

  def show
    @link = Link.find(params[:id])
    @comments = @link.comments.select { |comment| comment.parent_comment == nil }
  end

  def new
  end

  def create
    @link = Link.new(params[:link])
    if @link.save
      redirect_to links_url
    else
      render :new
    end
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_filter :authenticate_user, :only => :destroy
  def new
  end

  def create
    @user = User.find_by_username(params[:username])


    p @user

    if @user && @user.authenticate_password(params[:password])
      session[:token] = @user.reset_session_token
      @user.save
      redirect_to users_url
    else
      flash[:notice] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    user = current_user
    user.session_token = nil
    user.save
    session[:token] = nil
    @current_user = nil
    render :new
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :authenticate_user
  def index
    @subs = Sub.all
  end

  def new
  end

  def create
    @sub = Sub.new(params[:sub])
    if @sub.save
      redirect_to subs_url
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      #log in
      redirect_to user_url(@user) #change this later
    else
      flash[:notice] = "Failed to create user"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    if session[:token]
      @current_user ||= User.find_by_session_token(session[:token])
    else
      nil
    end
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<!-- <p>
<%= comment.author.username %>:<br>
<%= comment.body %>
<%= link_to "Reply to this comment",
    link_comment_url(comment.link_id, comment) %>
</p> -->
<li>
    <%= comment.author.username %>
    <%= comment.body %>
    <%= link_to "Reply to this comment",
        link_comment_url(comment.link_id, comment) %>

    <% unless comment.sub_comments.empty? %>
      <ul>

        <%= render comment.sub_comments %>
        <br>
      </ul>
    <% end %>
</li>

app/views/comments/new.html.erb
<h1>Comment on <%= @link.title %></h1>

<form action="<%= sub_link_comments_url %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="form_authenticity_token">

  <label for="comment">Comment on this post:</label>
  <input type="text" name="comment[body]" id="comment">

  <input type="submit" value="Submit Comment">

</form>

app/views/comments/show.html.erb
<h1>Viewing Comment</h1>
<%= @comment.author.username %>:
<br>
<%= @comment.body %>
<br><br>

<form action="<%= link_comments_url %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="form_authenticity_token">
  <input type="hidden" name="parent_comment"
    value="<%= @comment.id %>">
  <input type="hidden" name="comment[link_id]" value="<%= @comment.link_id %>">
  <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">
  <label for="comment">Comment on this post:</label>
  <input type="text" name="comment[body]" id="comment">

  <input type="submit" value="Submit Reply">

</form>
<h2>Replies To This Comment</h2>
<%= render @replies %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] if flash[:notice] %>
  <% if logged_in? %>
  Logged in as: <%= current_user.username %>
  <%= button_to "Sign Out", logout_url, method: :delete %>
  <% else %>
  Sign In: <%= link_to "Sign In", login_url %>
  Sign Up: <%= link_to "Sign Up", new_user_url %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<form action="<%= new_link_url %>" method="post">
  <% if @edit %>
  <input type="hidden" name="_method" value="put">
  <% end %>
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="hidden" name="link[submitter_id]"
    value="<%= current_user.id %>">

  <label for="link_title">Title:</label>
  <input type="text" name="link[title]"
     value="<%= @link.title if @link %>" id="link_title">

  <label for="link_url">URL:</label>
  <input type="text" name="link[url]"
     value="<%= @link.url if @link %>" id="link_url">

  <% if @edit %>
  <input type="submit" value="Edit Link">
  <% else %>
  <input type="submit" value="Create Link">
  <% end %>
</form>

app/views/links/_link.html.erb
<p>
<%= link_to link.title, link_url(link) %>
</p>

app/views/links/edit.html.erb
<%= render :partial => "form" %>

app/views/links/index.html.erb
<%= render @links %>

app/views/links/new.html.erb
<h1>Submit New Link</h1>
<%= render partial: "form" %>

app/views/links/show.html.erb
<%= render @link %>

<form action="<%= link_comments_url(@link) %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="form_authenticity_token">
  <input type="hidden" name="comment[author_id]"
    value="<%= current_user.id %>">
  <input type="hidden" name="comment[link_id]" value="<%= @link.id %>">

  <label for="comment">Comment on this Link:</label>
  <input type="text" name="comment[body]" id="comment">

  <input type="submit" value="Submit Comment">
</form>

<%= render @comments %>

app/views/session/new.html.erb
<h1>Sign In</h1>
<form action="<%= login_url %>" method="post">

  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="username">Username:</label>
  <input type="text" name="username" id="username">

  <label for="password">Password:</label>
  <input type="password" name="password" id="password">

  <input type="submit" value="Sign In">

</form>

app/views/subs/index.html.erb
<% @subs.each do |sub| %>
<%= link_to sub.name, sub_links_url(sub) %>
<% end %>

app/views/subs/new.html.erb
<h1>Create New Sub</h1>
<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="hidden" name="sub[moderator_id]"
    value="<%= current_user.id %>">

  <label for="sub_name">Name:</label>
  <input type="text" name="sub[name]" id="sub_name">
  <br>
  <br>

  <h3>Submit Links</h3>

  <% 5.times do |i| %>
  <input type="hidden" name="sub[links_attributes][<%= i %>][submitter_id]"
    value="<%= current_user.id %>">
  <input type="hidden"

  <label for="title">Title:</label>
  <input type="text" name="sub[links_attributes][<%= i %>][title]" id="title">

  <label for="url">URL:</label>
  <input type="text" name="sub[links_attributes][<%= i %>][url]" id="url">
  <br>

  <% end %>


  <input type="submit" value="Create New Sub">

</for>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_email">Email:</label>
  <input type="text" name="user[email]" id="user_email">

  <label for="user_username">Username:</label>
  <input type="text" name="user[username]" id="user_username">

  <label for="user_password">Password:</label>
  <input type="password" name="user[password]" id="user_password">

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<%= @user.username %>